name: fos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: "^0.12.0"
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/home/
    - assets/images/nav/
    - assets/images/onboard/
    - assets/fonts/
