name: fos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  form_field_validator: ^1.1.0
  get_storage: ^2.0.3
  image_picker: ^0.8.7+3
  dio: ^4.0.6
  retrofit: ^3.3.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0

  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.1
  firebase_auth: ^4.2.2
  firebase_storage: ^11.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: "^0.12.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/home/
    - assets/images/nav/
    - assets/images/onboard/
    - assets/fonts/
